### ISSUE TITLE
convert codes to jupyter notebooks

### ISSUE THREAD

**Issue by AnirudhSubramanyam** [Subramanyam-Lab/IE496_NHTS#2]
I think we should convert the raw `.py` files to `.ipynb` notebooks. Can one of you look into this? @eduardolopez13 @theSubsurfaceGuy

**Comment by wkaleem** [comment]
Issue resolved @eduardolopez13 can you please merge the same? thank you.

**Comment by eduardolopez13** [comment]
Just merged, thank you Waquar
